name: goyerv_support_web_app
description: Guides on various topics as regards to Goyerv and how users can navigate their way around the Goyerv platform as a user/runner

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter

  web: ^1.1.1
  
  # svg_renderer
  flutter_svg: ^2.0.7
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  
  # font_awesome
  font_awesome_flutter: ^10.5.0
  
  # http
  http: ^1.2.2

  # flutter_bloc
  flutter_bloc: ^8.0.1

  # equatable
  equatable: ^2.0.3

  # stream_transform
  stream_transform: ^2.0.0

  # shared_preferences
  shared_preferences: ^2.2.1

  # Provider
  provider: ^6.0.2

  # data checker
  internet_connection_checker: ^3.0.1

  # dartz
  dartz: ^0.10.1

  # get_it
  get_it: ^8.0.3

  # intl
  intl: ^0.20.2

  # rich_text
  rich_text_controller: ^2.0.1

  # url_launcher
  url_launcher: ^6.1.6

  # detectable_text_field
  detectable_text_field: ^3.0.2

  # encrypt
  encrypt: ^5.0.3

  # file_picker
  file_picker: ^8.1.6

  # universal
  universal_io: ^2.2.2
  
  # protobuf
  protobuf: ^3.1.0
  
  # go router
  go_router: ^14.8.1

  # footer
  footer: ^0.0.4

  # share plus
  share_plus: ^10.1.4

  # shimmer
  shimmer: ^3.0.0

  # timeago
  timeago: ^3.7.0

  #uuid
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # THICCCBOI FONT [https://github.com/wonderunit/font-thicccboi]
  fonts:
    - family: THICCCBOI
      fonts:
        - asset: assets/fonts/THICCCBOI-Black.ttf
          weight: 900

        - asset: assets/fonts/THICCCBOI-Bold.ttf
          weight: 700

        - asset: assets/fonts/THICCCBOI-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/THICCCBOI-Light.ttf
          weight: 300

        - asset: assets/fonts/THICCCBOI-Medium.ttf
          weight: 500

        - asset: assets/fonts/THICCCBOI-Regular.ttf
          weight: 400

        - asset: assets/fonts/THICCCBOI-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/THICCCBOI-ThicccAF.ttf
          weight: 900

        - asset: assets/fonts/THICCCBOI-Thin.ttf
          weight: 100

  # To add assets to your application, add an assets section, like this:
  assets:

    #  Images / Illustrations 
    - assets/images/icon.png
    - assets/images/goyerv_logo.svg
    - assets/images/goyerv_logo.png
    - assets/images/coffee_light.svg
    - assets/images/coffee_dark.svg
    - assets/images/LinkedIn_logo.svg
    - assets/images/X_logo.svg

    # SVGs
    - assets/images/android.svg
    - assets/images/apple.svg
    - assets/images/linux.svg
    - assets/images/windows.svg


    # Languages
    - assets/languages/zh-CN.json
    - assets/languages/zh-TW.json
    - assets/languages/en.json
    - assets/languages/fr.json
    - assets/languages/hi.json
    - assets/languages/ja.json
    - assets/languages/es.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
